api_platform:
    title: AquaGestion
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json: [ 'application/json' ]
        # tu peux commenter jsonld ou ne pas le définir du tout
        # jsonld: ['application/ld+json']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header